services:
  db:
    image: postgres:16
    container_name: saas_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-saas_db}
    ports:
      - "5432:5432"
    volumes:
      - saas_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d saas_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  saas_db_data:

restart: unless-stopped #Helps keep DB running after reboot/crashes